### ISSUE TITLE
'Set' is undefined in IE 11 document mode 10

### ISSUE THREAD

**Issue by holysnake91** [wmonk/create-react-app-typescript#169]
Getting this error 'Set' is undefined in IE 11 document mode 10.

If change to document mode 11 no issue, but we can't control the user IE settings.

Attached the picture where the code giving the issue.

![image](https://user-images.githubusercontent.com/15364241/31000528-c53d5e52-a50e-11e7-85dc-6a60c30ad43d.png)

**Comment by Paradox22** [comment]
React 16 requires polyfilling [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) and [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set): https://reactjs.org/docs/javascript-environment-requirements.html

This fixes the problem for production builds, but I haven't been able to get it working in development mode. I'm guessing it requires modifying webpack config, but this in turn requires ejecting and I would like to avoid that.

There is a [discussion](https://github.com/facebookincubator/create-react-app/pull/3200) in create-react-app repository about including these polyfills by default.

**Comment by holysnake91** [comment]
Yes after add the
import 'core-js/es6/map';
import 'core-js/es6/set';

it work for the production build

**Comment by wmonk** [comment]
@holysnake91 is this fixed now, if so please close this issue 😄

**Comment by holysnake91** [comment]
It only work on production build nut not dev build

**Comment by DorianGrey** [comment]
As mentioned by @Paradox22 , it is still under discussion about if and how to include these polyfills, since they are required for the majority of the browsers, thus generating additional bundle size without any benefit.
The consideration ticket can be found here:
https://github.com/facebookincubator/create-react-app/issues/3343

Due to the intended feature parity, I'd say we should not go ahead with a different way here. Until then, you have polyfill your project properly yourself.

Until then, including appropriate polyfills **before the first import** of `react` (e.g. on top of the `index.tsx`) will help. E.g. using `core-js`.
```
import 'core-js/es6/map';
import 'core-js/es6/set';
```
