### ISSUE TITLE
Failure importing images

### ISSUE THREAD

**Issue by galvesribeiro** [wmonk/create-react-app-typescript#172]
Hello folks,

I was trying to follow https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-images-fonts-and-files to import png images but, sadly, I'm getting "module not found".

Can anyone shed a light on what may be wrong?

Thank you!

Appreciate any help!

**Comment by pscanf** [comment]
Probably you need a type definition for the module. For example, for `.png` images add the following file to your project:

```ts
// typings/png.d.ts
declare module "*.png";
```

This tells the compiler that modules whose name ends in `.png` exist and export a value of type `any`:

```ts
import src from "image.png";
// module found, src is of type any
```

If the file actually doesn't exist (because you mis-spelled it for instance) the compiler won't warn you anymore though, but in that case webpack will complain telling you "module not found".

**Comment by galvesribeiro** [comment]
@pscanf thanks for the reply.

I found the same conclusion here:

```
declare module '*.jpg' {
    let _: string
    export = _
}

declare module '*.png' {
    let _: string
    export = _
}
```

That made the thing work properly. Sorry, I forgot to get back here and close the issue.

Thanks!

**Comment by joshtynjala** [comment]
I had to find this issue to figure out why I couldn't import a PNG file, even though README.md said that it should be possible.

With that in mind, I'm not so sure that this issue should be closed. I don't mind adding a *.d.ts* file to my project, but either the *.d.ts* file should be created automatically for me or the documentation should explain that it's required.

**Comment by wmonk** [comment]
@joshtynjala fancy writing some documentation in the README?

**Comment by joshtynjala** [comment]
@wmonk I'll try to look into it tomorrow!
