### ISSUE TITLE
Failure to create new app

### ISSUE THREAD

**Issue by AJamesPhillips** [wmonk/create-react-app-typescript#18]
### Can reproduce the problem with latest npm

npm: 4.1.2  Node: v7.4.0

### Description

I'm running as non root, on Ubuntu 14.04.5 inside a vagrant virtualbox:

    $ create-react-app kanban --scripts-version=react-scripts-ts

### Expected behavior

It should create a new Typescript React app.

### Actual behavior

It errors with:

    no such file or directory, chmod '/vagrant/kanban/node_modules/esprima/bin/esparse.js'

### Environment

Run in the project folder:

1. `npm ls react-scripts`: 

    kanban@0.1.0 /vagrant/kanban
    └── (empty)

2. `node -v`: 

    v7.4.0

3. `npm -v`:

    4.1.2

Operating system:

    Ubuntu 14.04.5 inside a vagrant virtualbox

#### Also recreatable with:
Node v7.4.0 npm v4.0.5
Node v6.9.4 npm  v3.10.10

[npm-debug node v7.4.0 npm v4.1.2.txt](https://github.com/wmonk/create-react-app-typescript/files/734952/npm-debug.node.v7.4.0.npm.v4.1.2.txt)

[npm-debug node v6.9.4 npm v3.10.10.txt](https://github.com/wmonk/create-react-app-typescript/files/734957/npm-debug.node.v6.9.4.npm.v3.10.10.txt)

### NOT re-creatable with:
Node v4.7.2
npm v2.15.11

**Comment by wmonk** [comment]
Hey @AJamesPhillips, thanks for reporting this! After a quick google this seems to be an issue with `npm` itself. When you create a new react-app it installs a bunch of packages using `npm` so I assume it's because of that.

If you look [here](https://github.com/npm/npm/issues/10800), there seems to be a bunch of conversation around npm versions, but it seems as you've tried two versions it might be something else. Are you able to install using [`yarnpkg`](https://yarnpkg.com/), I think CRA will use `yarn` by default if it's installed.

**Comment by AJamesPhillips** [comment]
Hey, no worries.  When you say:

> conversation around npm versions, but it seems as you've tried two versions it might be something else

I'm confused as I think it's definitely something to do with how different versions of npm behave right?  As it's working for the moment and [this is more pressing](https://github.com/facebookincubator/create-react-app/pull/1459) I won't be able to try installing with yarn for a while but will try when I can reprioritise it.  Regardless, thank you very much for your prompt reply 👍  😄

**Comment by wmonk** [comment]
Currently I have 
```
→ node -v
v7.3.0
→ npm -v
3.10.10
```
and it's working fine. That is on OS X though so guess it's OS specific.
