### ISSUE TITLE
mixing .js/.jsx and .ts/.tsx

### ISSUE THREAD

**Issue by michabu** [wmonk/create-react-app-typescript#19]
First of all I want to thank you for your great work. I've started to use typescript with my IDE (idea) which worked fine but would result in not being able to `npm run` without first compiling in the IDE. So I was really happy when I found this fork.

I create this issue to clarify if I get it right that .js and .jsx files will not be transpiled?

If that is so: Is there a technical reason for this? Because in an existing project I would have to rename all files to be able to use create-react-app-typescript instead of beeing able to gradually move over. Is there a way to enable compiling of both .js and .ts Files?

Thank you for your help!

**Comment by wmonk** [comment]
Hi @michabu, no problem 😄 !

You are correct, `react-scripts-ts` will not compile js or jsx files. You can see in [this commit](https://github.com/wmonk/create-react-app-typescript/commit/9135f06260ec3b343b7a4b47acf25106eeef1c07#diff-d2bddbd3bfb7051f9381474c844674faL149) that babel-loader was removed from the webpack config. You are still able to require js files, but they will not be run through babel. I suppose the reason for this is to keep the package as slim as possible, if you're writing typescript, it's unlikely you need the babel transpiler as well. I think CRA promotes starting new projects, rather than retrofitting into old projects.

If you want to add back in the babel loader, you can run `npm run eject`, and then update the webpack config yourself. **Be warned, this is a permanent action**! However, you could do something clever with git, wherein you eject, update the config, and commit in one go. Then to use `react-scripts-ts` again in the future, you could revert that commit. I've not tried this myself, and is only a thought, so take it with a pinch of salt 😄

**Comment by michabu** [comment]
Thank you @wmonk for the answer. In the meantime I managed to rename everything in my project to .ts / .tsx and types. Since my project was not to big yet that was doable.

As I understand it the option allowJs=true in tsconfig.json should theoretically allow to just "do a quick sanity check" on .js files and otherwise pass them through to the output folder to allow for a smooth transition. It didn't work for me though. But wouldn't that theoretically be an option for people wanting to add the benefits of typescript without the pain of having to rename / add types to everything in an existing project?

After all it is a great addition (imho) to have the types around. It already helped me catch and understand a couple of issues with my code.

Thanks again @wmonk for making using ts with react-scripts possible.

**Comment by wmonk** [comment]
@michabu, glad you got it sorted! Not sure about getting it to work incrementally, I suppose updating the webpack config should be enough though.

**Comment by sandys** [comment]
@wmonk sorry for commenting on an old bug, but i didnt want to create a new one. we are looking at migrating a big jsx project to tsx as well. and we would love to use your infrastructure. is it not possible to have babel as an optional dependency (or some other way to run jsx ) ?

having a large single cutover is going to be extremely hard for a lot of projects like us.
