### ISSUE TITLE
VS Code - debugging tests - cannot connect to runtime process, timeout after 10000 ms

### ISSUE THREAD

**Issue by MatejMazur** [wmonk/create-react-app-typescript#209]
### Is this a bug report?

Yes

### Can you also reproduce the problem with npm 4.x?

Yes

### Which terms did you search for in User Guide?

react-scripts-ts vs code debug
react-scripts-ts vs code debug tests
typescript jest vs code Cannot connect to runtime process, timeout after 10000 ms
vs code Cannot connect to runtime process, timeout after 10000 ms
...

### Environment

1. `node -v`: 8.9.1
2. `npm -v`: 5.5.1
3. `yarn --version` (if you use Yarn):
4. `npm ls react-scripts-ts` (if you haven’t ejected): 2.8.0

Then, specify:

1. Operating system: Windows 10
2. Browser and version (if relevant): -

### Steps to Reproduce

1. create project with create-react-app --scripts-version=react-scripts-ts
2. set debugging tests
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug CRA Tests",
      "type": "node",
      "request": "launch",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/react-scripts-ts",
      "runtimeArgs": [
        "--inspect-brk",
        "test"
      ],
      "args": [
        "--runInBand",
        "--no-cache"
      ],
      "cwd": "${workspaceRoot}",
      "protocol": "inspector",
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen"
    }
  ]
}
```
3. run debugging test in VS Code

### Expected Behavior

It should start the debugging of tests.

### Actual Behavior

Until a few seconds it shows error message:
![image](https://user-images.githubusercontent.com/20944757/34055695-ba9fbe00-e1d0-11e7-9244-da8f288b40aa.png)

**Comment by DorianGrey** [comment]
The configuration you mentioned does no longer work in VS Code 1.19 and above, and regarding the issues listed in the VS Code repo, it only worked before due to a bug. See the comment from @weinand:
https://github.com/Microsoft/vscode/issues/40293#issuecomment-352010762

The updated config should look like this (adopted):
```
{
    "name": "Debug CRA Tests",
    "type": "node",
    "request": "launch",
    "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/react-scripts-ts",
    "args": [
      "test",
      "--runInBand",
      "--no-cache",
      "--env=jsdom"
    ],
    "cwd": "${workspaceRoot}",
    "protocol": "inspector",
    "console": "integratedTerminal",
    "internalConsoleOptions": "neverOpen"
}
```
A quick check with VS Code 1.19 on Win 10 with a freshly generated app confirmed that this works fine.

References:
- Issue on CRA: https://github.com/facebookincubator/create-react-app/issues/3602
- Issue on VS Code: https://github.com/Microsoft/vscode/issues/40293

**Comment by Guria** [comment]
When I last tried debugging in vs code + chrome it catched breakpoints only after page refresh. The same was about original CRA as well.
