### ISSUE TITLE
create-react-app config typescript but error “is not sorted alphabetically

### ISSUE THREAD

**Issue by mazhiwen** [wmonk/create-react-app-typescript#324]
create-react-app config with typescript but error “is not sorted alphabetically
 related issues: [https://github.com/ant-design/ant-design/issues/10533
](url)
program build with :
[http://ant.design/docs/react/use-in-typescript-cn
](url)
this is the order steps:
yarn create react-app antd-demo-ts --scripts-version=react-scripts-ts
yarn add react-app-rewired --dev
yarn add ts-import-plugin --dev
### config-overrides.js：
tsLoader.options = {
getCustomTransformers: () => ({
before: [ tsImportPluginFactory({
libraryName: 'antd',
libraryDirectory: 'es', //this line get error
style: 'css',
}) ]
})
};
I change the position of libraryName libraryDirectory ,then go right.
i want to know why 

excute yarn start
### error
 xxxxx/config-overrides.js(22,11): The key 'libraryDirectory' is not sorted alphabetically

**Comment by DorianGrey** [comment]
The error itself should be descriptive enough, shouldn't it? ([More details](https://github.com/palantir/tslint/blob/88d6a144a86519513ced4ce906483272c1a1bbaa/src/rules/objectLiteralSortKeysRule.ts))
It will be gone if you change
```javascript
before: [ tsImportPluginFactory({
    libraryName: 'antd',
    libraryDirectory: 'es',
    style: 'css',
}) ]
```
into
```javascript
before: [ tsImportPluginFactory({
    libraryDirectory: 'es',
    libraryName: 'antd',
    style: 'css',
}) ]
```

Alternatively, you may update the `exclude` key in the project's `tslint.json` by adding `config-overrides.js` to it.
Since the `allowJs` flag is set in the project's `tsconfig`, the linter will also pick up `.js` files and apply any rules that are applicable on them. The key ordering on hash definitions is one of them.
