### ISSUE TITLE
[Feature] Use babel

### ISSUE THREAD

**Issue by inssein** [wmonk/create-react-app-typescript#36]
It seem's like a decision was made not to use babel? Just testing out this project and realized some things do not get auto polyfill-ed. For example, any usage of Array.find won't work on older browsers.

**Comment by heyimalex** [comment]
I think the decision was made to drop babel because its removal simplifies things a bit and tsc has no issues compiling syntax down (classes, arrow functions, imports, async/await, etc). Apparently tsc doesn't do pollyfills though. [Here's an issue with some relevant discussion](https://github.com/Microsoft/TypeScript/issues/6468). Just chiming in with some more info.

**Comment by chadedrupt** [comment]
If it is just polyfills you require then you can simply import `babel-polyfill`.
