### ISSUE TITLE
Update TSLint to v5?

### ISSUE THREAD

**Issue by victordidenko** [wmonk/create-react-app-typescript#40]

**Comment by wmonk** [comment]
Will accept a PR for this!

**Comment by mindjuice** [comment]
Also, I'm wondering about the use of carets for packages like `tslint`, `tslint-loader`, etc. (e.g., `"tslint": "^5.2.0",`).

Since these packages are only installed and run from the `react-scripts-ts` folder, is there any reason not to just list the specific version with no caret as is done for most other packages in `react-scripts-ts`?

Thanks!
