### ISSUE TITLE
React Native version

### ISSUE THREAD

**Issue by pierre-H** [wmonk/create-react-app-typescript#48]
Hello !
Is it possible to create a new version for React Native from react-community/create-react-native-app ?
Thank you in advance for your answer !

**Comment by wmonk** [comment]
I'm not sure how this would work to be honest. Their repo doesn't seem to be forked from the original facebook one, so is inherently incompatible with react-scripts-ts. I would accept a guide in a  PR if you can provide one.

**Comment by DanielRosenwasser** [comment]
The React Native setup is fairly minimal anyway once you've spent 18 hours getting Android Studio working. Check out https://github.com/Microsoft/TypeScript-React-Native-Starter which I also wrote if you'd like to get TypeScript wired up w/ RN. It's not entirely smooth, but with changes coming to the React Native Packager, it'll get much better.

**Comment by pierre-H** [comment]
For anyone who tries to use TypeScript with CRNA, check this : 
https://github.com/react-community/create-react-native-app/issues/87#issuecomment-296097125

**Comment by brentvatne** [comment]
Hi @wmonk!

> I'm not sure how this would work to be honest. Their repo doesn't seem to be forked from the original facebook one, so is inherently incompatible with react-scripts-ts. I would accept a guide in a PR if you can provide one.

We took create-react-app as a base and built create-react-native-app (Expo in collaboration with Facebook) using the same code but throwing away / rewriting whatever didn't apply to react-native. It's a fork but without preserving git history. It will indeed be incompatible with react-scripts-ts as it turns out that a lot of it is very different from CRA.

------------------------------------------------------------------

Hey @DanielRosenwasser! Wow thanks a lot for putting that together, it looks very comprehensive.

> The React Native setup is fairly minimal anyway once you've spent 18 hours getting Android Studio working (tip: on Windows I was better off using a physical device).

I think this is true if you are a smart, experienced engineer at Microsoft, but it is also certainly not ideal. Additionally, it certainly is a pain to just get Android Studio set up but it doesn't stop there -- what if you want to set up iOS as well? and what if you want to try out iOS and you're on Windows? The time-to-hello-world (TTHW) is too high, and in some cases not possible (React Native iOS development from Windows) without using Create React Native App (CRNA).

CRNA will be recommended in the [Quick Start guide for React Native starting in React Native 0.45](http://facebook.github.io/react-native/releases/0.45/docs/getting-started.html) so you will be getting more questions about this.

We would be happy to work with you to make TypeScript integration in CRNA a breeze, let us know how we can help.

**Comment by wmonk** [comment]
@DanielRosenwasser @brentvatne it would definitely be cool to put together some kind of guide of how to get ts working in CRNA and visa versa! Not sure if it's something that would live here though?

**Comment by DanielRosenwasser** [comment]
@brentvatne I definitely agree. Sorry I didn't get to respond to this (it was EOD Friday). I think long term I want to make the process as easy as possible. Short term, I want to make it at least somewhat possible. 😄 

I think things will be getting better thanks to metro-bundler. I'll email you soon to try to open up some discussion from our end. Thanks for reaching out!

**Comment by wmonk** [comment]
As this hasn't been updated for a while, I am closing this issue. Please re-open if we have an update.
